version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: advocacia_db
    restart: always
    environment:
      POSTGRES_DB: advocacia
      POSTGRES_USER: advocacia
      POSTGRES_PASSWORD: advocacia@ad  # ALTERE ISSO!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U advocacia"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: